services:
  - type: web
    name: e-commerce-backend
    env: node
    plan: free
    rootDir: BACKEND
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Set this in Render Dashboard (e.g., MongoDB Atlas URI)
      - key: DB_NAME
        value: e-Commerce
      - key: REDIS_HOST
        fromService:
          type: redis
          name: cache
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: cache
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: cache
          property: password

  - type: redis
    name: cache
    plan: free
    ipAllowList: [] # Only allow internal connections
